name: Brittany P. Boribong
url: boribong.github.io
description: Senior Scientist, Immunology at DropGenie

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
